namespace OpenGen;

public partial class OpenGen
{
    private static readonly Dictionary<ushort, string> WeaponClasses = new()
    {
        // weapons
        { 1,   "weapon_deagle" },
        { 2,   "weapon_elite" },
        { 3,   "weapon_fiveseven" },
        { 4,   "weapon_glock" },
        { 30,  "weapon_tec9" },
        { 32,  "weapon_hkp2000" },
        { 36,  "weapon_p250" },
        { 61,  "weapon_usp_silencer" },
        { 63,  "weapon_cz75a" },
        { 64,  "weapon_revolver" },
        { 7,   "weapon_ak47" },
        { 8,   "weapon_aug" },
        { 10,  "weapon_famas" },
        { 13,  "weapon_galilar" },
        { 16,  "weapon_m4a1" },
        { 39,  "weapon_sg556" },
        { 40,  "weapon_ssg08" },
        { 60,  "weapon_m4a1_silencer" },
        { 9,   "weapon_awp" },
        { 11,  "weapon_g3sg1" },
        { 38,  "weapon_scar20" },
        { 17,  "weapon_mac10" },
        { 19,  "weapon_p90" },
        { 23,  "weapon_mp5sd" },
        { 24,  "weapon_ump45" },
        { 26,  "weapon_bizon" },
        { 33,  "weapon_mp7" },
        { 34,  "weapon_mp9" },
        { 14,  "weapon_m249" },
        { 25,  "weapon_xm1014" },
        { 27,  "weapon_mag7" },
        { 28,  "weapon_negev" },
        { 29,  "weapon_sawedoff" },
        { 35,  "weapon_nova" },

        // knives
        { 42,  "weapon_knife" },
        { 59,  "weapon_knife_t" },
        { 500, "weapon_knife_bayonet" },
        { 503, "weapon_knife_css" },
        { 505, "weapon_knife_flip" },
        { 506, "weapon_knife_gut" },
        { 507, "weapon_knife_karambit" },
        { 508, "weapon_knife_m9_bayonet" },
        { 509, "weapon_knife_tactical" },
        { 512, "weapon_knife_falchion" },
        { 514, "weapon_knife_survival_bowie" },
        { 515, "weapon_knife_butterfly" },
        { 516, "weapon_knife_push" },
        { 517, "weapon_knife_cord" },
        { 518, "weapon_knife_canis" },
        { 519, "weapon_knife_ursus" },
        { 520, "weapon_knife_gypsy_jackknife" },
        { 521, "weapon_knife_outdoor" },
        { 522, "weapon_knife_stiletto" },
        { 523, "weapon_knife_widowmaker" },
        { 525, "weapon_knife_skeleton" },
        { 526, "weapon_knife_kukri" },
    };

    // knife models
    private static readonly Dictionary<ushort, string> KnifeModels = new()
    {
        { 42,  "models/weapons/v_knife_default_ct.vmdl" },
        { 59,  "models/weapons/v_knife_default_t.vmdl" },
        { 500, "models/weapons/v_knife_bayonet.vmdl" },
        { 503, "models/weapons/v_knife_css.vmdl" },
        { 505, "models/weapons/v_knife_flip.vmdl" },
        { 506, "models/weapons/v_knife_gut.vmdl" },
        { 507, "models/weapons/v_knife_karam.vmdl" },
        { 508, "models/weapons/v_knife_m9_bay.vmdl" },
        { 509, "models/weapons/v_knife_tactical.vmdl" },
        { 512, "models/weapons/v_knife_falchion.vmdl" },
        { 514, "models/weapons/v_knife_survival_bowie.vmdl" },
        { 515, "models/weapons/v_knife_butterfly.vmdl" },
        { 516, "models/weapons/v_knife_push.vmdl" },
        { 517, "models/weapons/v_knife_cord.vmdl" },
        { 518, "models/weapons/v_knife_canis.vmdl" },
        { 519, "models/weapons/v_knife_ursus.vmdl" },
        { 520, "models/weapons/v_knife_gypsy_jackknife.vmdl" },
        { 521, "models/weapons/v_knife_outdoor.vmdl" },
        { 522, "models/weapons/v_knife_stiletto.vmdl" },
        { 523, "models/weapons/v_knife_widowmaker.vmdl" },
        { 525, "models/weapons/v_knife_skeleton.vmdl" },
        { 526, "models/weapons/v_knife_kukri.vmdl" },
    };
}
